### PR TITLE
Batched Updates

### PR DESCRIPTION
**Pull request by gilesknap**
A minor change to tree.py to allow batches of changes to pixels. See updated README.md for details.

This change allows for much faster animations of the lights.

Also includes:

- example flow.py which uses the batch feature and implements rows of colour flowing up the tree
- README.md updated to describe the changes in this PR
- example rc.local for auto-starting the tree animation on power up

### CODE REVIEW

**Comment by gilesknap** [comment]
Hi @bennuttall (thanks for a great project!) Your profile mentions that you are not working for Raspberry Pi anymore. Is there anyone else taking over maintenance of this repo? There are a couple of long term PRs awaiting review.

If you are looking for a volunteer then I'd be happy to look after the repo. 

Thanks,
giles

**Comment by bennuttall** [comment]
Hi and thanks for the contribution. Looking at the 3 PRs I don't think they add value to what's supposed to be a fairly simple getting started resource. They're all valid contributions, but they're unnecessary changes that only add complexity or general Linux/Python usage that is information better sought elsewhere. These are the kinds of thing that would be better served as a blog post or other third-party resource.

Generally I'll accept corrections and fixes but not additions here.

Thanks

**Comment by gilesknap** [comment]
Thanks for the feedback @bennuttall. Perhaps I overloaded the PR with the stuff I'd been working on - I think the few lines of change to tree.py to provide batched update are generally useful and make the possibilities a bit more compelling out of the box. If you would like me to resubmit just tree.py changes then let me know. 

It could be considered a fix to #21 perhaps.

Cheers.

**Comment by b-morgan** [comment]
I have to agree with @gilesknap. I believe the changes to tree.py are minimal and add useful functionality. The example and the documentation changes just support and document the tree.py changes, and better documentation is always a good thing, IMO.

@bennuttall, please reconsider accepting this pull request.

**Pull request closed without merging**
